import { app,net,type ClientRequest,type Session } from 'electron'
import { closeSync,ftruncateSync,openSync,writeSync } from 'node:fs'
import { join } from 'node:path'
import type { DownloadRepository } from '../domain/download-repository'
interface Segment{start:number;end:number;received:number;done:boolean}
interface ActiveDownload{requests:Set<ClientRequest>;segments:Segment[];file:number;paused:boolean;cancelled:boolean;lastBytes:number;lastTime:number;lastNotify:number}
export class ElectronDownloadEngine{
  private readonly active=new Map<string,ActiveDownload>()
  constructor(private session:Session,private repo:DownloadRepository,private changed:()=>void,private finished:(id:string)=>void){}
  isBusy(){return this.active.size>0} isActive(id:string){return this.active.has(id)}
  async start(id:string,url:string,fileName:string){if(this.active.has(id))return;const item=this.repo.get(id);if(!item)return;try{const probe=await this.probe(url);const savePath=join(app.getPath('downloads'),fileName);const file=openSync(savePath,'w+');if(probe.total>0)ftruncateSync(file,probe.total);const count=probe.ranges&&probe.total>0?Math.min(item.segmentCount??1,probe.total):1;const size=probe.total>0?Math.ceil(probe.total/count):0;const segments=Array.from({length:count},(_,index)=>({start:index*size,end:probe.total>0?Math.min(probe.total-1,(index+1)*size-1):-1,received:0,done:false}));const state:ActiveDownload={requests:new Set(),segments,file,paused:false,cancelled:false,lastBytes:0,lastTime:Date.now(),lastNotify:0};this.active.set(id,state);item.savePath=savePath;item.totalBytes=probe.total;item.receivedBytes=0;item.segmentProgress=segments.map(()=>0);item.status='downloading';item.error=undefined;this.repo.save(item);this.changed();console.info('[Segmented download started]',{url,savePath,segments:count,totalBytes:probe.total});this.runSegments(id)}catch(error){this.fail(id,error)}}
  pause(id:string){const state=this.active.get(id),item=this.repo.get(id);if(!state||!item)return;state.paused=true;for(const request of state.requests)request.abort();state.requests.clear();item.status='paused';item.speed=0;this.repo.save(item);this.changed();console.info('[Download paused]',{url:item.url,receivedBytes:item.receivedBytes})}
  resume(id:string){const state=this.active.get(id),item=this.repo.get(id);if(!state||!item)return;state.paused=false;item.status='downloading';this.repo.save(item);this.changed();this.runSegments(id)}
  cancel(id:string){const state=this.active.get(id);if(!state)return;state.cancelled=true;for(const request of state.requests)request.abort();state.requests.clear();closeSync(state.file);this.active.delete(id);const item=this.repo.get(id);if(item){item.status='cancelled';item.speed=0;this.repo.save(item);this.changed()}this.finished(id)}
  private probe(url:string):Promise<{total:number;ranges:boolean}>{return new Promise((resolve,reject)=>{let settled=false;const request=net.request({url,method:'GET',session:this.session,redirect:'follow'});request.setHeader('Range','bytes=0-0');request.on('response',response=>{const header=(name:string)=>{const value=response.headers[name];return Array.isArray(value)?value[0]:value??''};const contentRange=header('content-range');const total=Number(contentRange.match(/\/(\d+)$/)?.[1]??header('content-length')??0);const ranges=response.statusCode===206;settled=true;resolve({total,ranges});request.abort()});request.on('error',error=>{if(!settled)reject(error)});request.end()})}
  private runSegments(id:string){const state=this.active.get(id),item=this.repo.get(id);if(!state||!item||state.paused||state.cancelled)return;for(const segment of state.segments.filter(value=>!value.done))this.runSegment(id,item.url,segment,state)}
  private runSegment(id:string,url:string,segment:Segment,state:ActiveDownload){const request=net.request({url,method:'GET',session:this.session,redirect:'follow'});state.requests.add(request);if(segment.end>=0)request.setHeader('Range',`bytes=${segment.start+segment.received}-${segment.end}`);request.on('response',response=>{if(response.statusCode>=400){this.fail(id,new Error(`Server returned HTTP ${response.statusCode}`));return}response.on('data',(chunk:Buffer)=>{if(state.paused||state.cancelled)return;writeSync(state.file,chunk,0,chunk.length,segment.start+segment.received);segment.received+=chunk.length;this.progress(id,state)});response.on('end',()=>{state.requests.delete(request);if(state.paused||state.cancelled)return;segment.done=true;if(state.segments.every(value=>value.done))this.complete(id,state)});response.on('error',error=>{state.requests.delete(request);if(!state.paused&&!state.cancelled)this.fail(id,error)})});request.on('error',error=>{state.requests.delete(request);if(!state.paused&&!state.cancelled)this.fail(id,error)});request.end()}
  private progress(id:string,state:ActiveDownload){const item=this.repo.get(id);if(!item)return;const bytes=state.segments.reduce((sum,value)=>sum+value.received,0),now=Date.now();item.receivedBytes=bytes;item.segmentProgress=state.segments.map(segment=>segment.end<0?0:Math.min(100,segment.received/(segment.end-segment.start+1)*100));item.speed=Math.max(0,(bytes-state.lastBytes)/Math.max(.001,(now-state.lastTime)/1000));state.lastBytes=bytes;state.lastTime=now;this.repo.save(item);if(now-state.lastNotify>150){state.lastNotify=now;this.changed()}}
  private complete(id:string,state:ActiveDownload){closeSync(state.file);this.active.delete(id);const item=this.repo.get(id);if(item){item.receivedBytes=state.segments.reduce((sum,value)=>sum+value.received,0);item.speed=0;item.status='completed';this.repo.save(item);this.changed();console.info('[Segmented download completed]',{url:item.url,segments:state.segments.length,bytes:item.receivedBytes})}this.finished(id)}
  private fail(id:string,error:unknown){const state=this.active.get(id);if(state){for(const request of state.requests)request.abort();try{closeSync(state.file)}catch{}this.active.delete(id)}const item=this.repo.get(id);if(item){item.status='failed';item.speed=0;item.error=error instanceof Error?error.message:String(error);this.repo.save(item);this.changed()}console.error('[Download failed]',error);this.finished(id)}
}
