import { app,type DownloadItem as ElectronItem,type Session } from 'electron'
import { join } from 'node:path'
import type { DownloadRepository } from '../domain/download-repository'
export class ElectronDownloadEngine{
  private active=new Map<string,ElectronItem>();private pendingId?:string
  constructor(private session:Session,private repo:DownloadRepository,private changed:()=>void,private finished:()=>void){session.on('will-download',(_event,download)=>this.attach(download))}
  isBusy(){return Boolean(this.pendingId)||this.active.size>0}
  isActive(id:string){return this.active.has(id)}
  start(id:string,url:string,fileName:string){if(this.pendingId)throw new Error('Please wait for the current download to start.');this.pendingId=id;const model=this.repo.get(id)!;model.fileName=fileName;this.repo.save(model);this.session.downloadURL(url)}
  private attach(download:ElectronItem){const id=this.pendingId;this.pendingId=undefined;if(!id){download.cancel();return}const model=this.repo.get(id);if(!model)return;const savePath=join(app.getPath('downloads'),download.getFilename());console.info('[Download started]',{url:download.getURL(),savePath});download.setSavePath(savePath);model.fileName=download.getFilename();model.savePath=savePath;model.status='downloading';this.repo.save(model);this.active.set(id,download);let lastBytes=0,lastTime=Date.now();download.on('updated',(_event,state)=>{const item=this.repo.get(id);if(!item)return;const now=Date.now(),received=download.getReceivedBytes();item.receivedBytes=received;item.totalBytes=download.getTotalBytes();item.speed=Math.max(0,(received-lastBytes)/Math.max(.001,(now-lastTime)/1000));item.status=state==='interrupted'?'interrupted':download.isPaused()?'paused':'downloading';item.error=state==='interrupted'?'Connection interrupted. Verify the server certificate or network, then retry.':undefined;lastBytes=received;lastTime=now;this.repo.save(item);this.changed()});download.once('done',(_event,state)=>{const item=this.repo.get(id);if(!item)return;item.receivedBytes=download.getReceivedBytes();item.totalBytes=download.getTotalBytes();item.speed=0;item.status=state==='completed'?'completed':state==='cancelled'?'cancelled':'failed';if(item.status==='failed')item.error='Download failed and cannot be resumed. Check the URL, TLS certificate, and network.';console.info('[Download finished]',{url:item.url,state,receivedBytes:item.receivedBytes,totalBytes:item.totalBytes});this.repo.save(item);this.active.delete(id);this.changed();this.finished()});this.changed()}
  pause(id:string){this.active.get(id)?.pause()} resume(id:string){this.active.get(id)?.resume()} cancel(id:string){this.active.get(id)?.cancel()}
}
