import { useEffect,useMemo,useState } from 'react'
import { Archive,CalendarClock,CheckCircle2,ChevronDown,ChevronRight,CirclePause,CirclePlay,FileArchive,FileText,Folder,FolderOpen,Globe2,HardDriveDownload,Link2,ListStart,Music2,Play,Settings,Square,Trash2,Video,X } from 'lucide-react'
import type { DownloadItem,DownloadQueue,DownloadStatus } from '../shared/download'

type Category='all'|'unfinished'|'finished'|'video'|'music'|'programs'|'documents'|'compressed'|'queues'|`queue:${string}`
const formatBytes=(value:number)=>value?`${(value/1024/1024).toFixed(value>10*1024*1024?2:3)} MB`:''
const ext=(name:string)=>name.split('.').pop()?.toLowerCase()??''
const videoTypes=['mp4','mkv','avi','mov','webm'];const musicTypes=['mp3','wav','aac','flac'];const docs=['pdf','doc','docx','txt','xls','xlsx'];const archives=['zip','rar','7z','tar','gz'];const programs=['exe','msi','dmg','deb','rpm','appimage']

export function App(){
  const [items,setItems]=useState<DownloadItem[]>([]),[queues,setQueues]=useState<DownloadQueue[]>([]),[category,setCategory]=useState<Category>('all'),[selected,setSelected]=useState<string>(),[selectedQueue,setSelectedQueue]=useState('main'),[dialog,setDialog]=useState(false),[scheduler,setScheduler]=useState(false),[options,setOptions]=useState(false),[detailId,setDetailId]=useState<string>(),[segmentCount,setSegmentCount]=useState(4),[fileSegments,setFileSegments]=useState(4),[context,setContext]=useState<{x:number;y:number;item:DownloadItem}>(),[url,setUrl]=useState(''),[error,setError]=useState('')
  useEffect(()=>{window.downloads.list().then(setItems);window.downloads.getSegmentCount().then(setSegmentCount);window.downloads.listQueues().then(value=>{setQueues(value);if(value[0])setSelectedQueue(value[0].id)});return window.downloads.onChanged(setItems)},[])
  const visible=useMemo(()=>items.filter(item=>matchesCategory(item,category)),[items,category])
  const current=items.find(item=>item.id===selected)
  async function add(queued=false){try{setError('');if(window.downloads.version<6)throw new Error('Restart Electron to load the segmented downloader update.');const item=queued?await window.downloads.enqueue(url.trim(),selectedQueue,fileSegments):await window.downloads.add(url.trim(),false,undefined,fileSegments);setSelected(item.id);if(!queued)setDetailId(item.id);setUrl('');setDialog(false)}catch(e){setError(e instanceof Error?e.message:'Unable to add download')}}
  const openQueueManager=()=>setScheduler(true)
  const stopAll=()=>items.filter(i=>i.status==='downloading').forEach(i=>window.downloads.pause(i.id))
  return <div className="idm-app">
    <div className="titlebar"><span><HardDriveDownload size={16}/> Internet Download Manager</span><div><button>—</button><button>□</button><button className="close">×</button></div></div>
    <div className="menubar"><button>Tasks</button><button>File</button><button>Downloads</button><button>View</button><button>Help</button><button>Donate</button></div>
    <div className="toolbar">
      <Tool icon={<Link2/>} label="Add URL" color="blue" onClick={()=>{setFileSegments(segmentCount);setDialog(true)}}/>
      <Tool icon={<CirclePlay/>} label="Resume" color="green" disabled={!current||!['queued','paused','interrupted','failed'].includes(current.status)} onClick={()=>current&&window.downloads.resume(current.id)}/>
      <Tool icon={<Square/>} label="Stop" color="red" disabled={!current||current.status!=='downloading'} onClick={()=>current&&window.downloads.pause(current.id)}/>
      <Tool icon={<CirclePause/>} label="Stop All" color="red" disabled={!items.some(i=>i.status==='downloading')} onClick={stopAll}/>
      <Tool icon={<Trash2/>} label="Delete" color="red" disabled={!current} onClick={()=>{if(current){window.downloads.cancel(current.id);setSelected(undefined)}}}/>
      <Tool icon={<X/>} label="Delete C..." color="gray" disabled={!items.some(i=>i.status==='completed')} onClick={()=>{window.downloads.deleteCompleted();if(current?.status==='completed')setSelected(undefined)}}/>
      <span className="separator"/>
      <Tool icon={<Settings/>} label="Options" color="blue" onClick={()=>setOptions(true)}/>
      <Tool icon={<CalendarClock/>} label="Scheduler" color="orange" onClick={()=>setScheduler(true)}/>
      <Tool icon={<ListStart/>} label="Start Queue" color="green" disabled={!selectedQueue} onClick={()=>window.downloads.startQueue(selectedQueue)}/>
      <Tool icon={<Square/>} label="Stop Queue" color="red" disabled={!selectedQueue} onClick={()=>window.downloads.stopQueue(selectedQueue)}/>
      <Tool icon={<Globe2/>} label="Grabber" color="blue"/>
    </div>
    <div className="workspace" onClick={()=>setContext(undefined)}><CategoryTree value={category} onChange={value=>{setCategory(value);if(value.startsWith('queue:'))setSelectedQueue(value.slice(6))}} items={items} queues={queues} onAdd={openQueueManager} onEdit={openQueueManager} onDelete={openQueueManager}/><DownloadTable items={visible} selected={selected} onSelect={setSelected} onOpen={setDetailId} onContext={(event,item)=>{event.preventDefault();setSelected(item.id);setContext({x:event.clientX,y:event.clientY,item})}}/></div>
    <div className="statusbar"><span>{items.filter(i=>i.status==='completed').length} completed</span><span>{items.filter(i=>i.status==='downloading').length} downloading</span><span>{items.length} file{items.length===1?'':'s'}</span><button onClick={()=>window.downloads.openFolder()}><FolderOpen size={13}/> Downloads</button></div>
    {dialog&&<div className="dialog-shade" onMouseDown={()=>setDialog(false)}><div className="dialog" onMouseDown={e=>e.stopPropagation()}><div className="dialog-title">Enter new address to download<button onClick={()=>setDialog(false)}>×</button></div><div className="dialog-body"><div className="url-row"><Globe2 size={42}/><div><label>Address</label><input autoFocus value={url} onChange={e=>setUrl(e.target.value)} onKeyDown={e=>e.key==='Enter'&&url.trim()&&add(false)} /></div></div>{error&&<p className="dialog-error">{error}</p>}<fieldset><legend>Download options</legend><label>Connections for this file <select value={fileSegments} onChange={e=>setFileSegments(Number(e.target.value))}>{[1,2,4,6,8].map(value=><option value={value} key={value}>{value}</option>)}</select></label><label>Download later in <select value={selectedQueue} onChange={e=>setSelectedQueue(e.target.value)}>{queues.map(queue=><option value={queue.id} key={queue.id}>{queue.name} ({queue.concurrency} files at once)</option>)}</select></label></fieldset></div><div className="dialog-actions"><button disabled={!url.trim()||!selectedQueue} onClick={()=>add(true)}>Download later</button><button className="primary" disabled={!url.trim()} onClick={()=>add(false)}>Start download</button><button onClick={()=>setDialog(false)}>Cancel</button></div></div></div>}
    {scheduler&&<SchedulerDialog queues={queues} initialQueue={selectedQueue} onClose={()=>setScheduler(false)} onSave={async(id,name,concurrency)=>{await window.downloads.updateQueue(id,name,concurrency);setQueues(await window.downloads.listQueues());setSelectedQueue(id)} } onCreate={async()=>{const queue=await window.downloads.createQueue('New download queue',1);setQueues(await window.downloads.listQueues());setSelectedQueue(queue.id);return queue}} onDelete={async id=>{await window.downloads.deleteQueue(id);const next=await window.downloads.listQueues();setQueues(next);setSelectedQueue(next[0]?.id??'');return next}}/>}
    {options&&<OptionsDialog segmentCount={segmentCount} onSave={async value=>{await window.downloads.setSegmentCount(value);setSegmentCount(value);setOptions(false)}} onClose={()=>setOptions(false)}/>} 
    {context&&<div className="row-context" style={{left:context.x,top:context.y}} onClick={e=>e.stopPropagation()}><button disabled={context.item.status!=='completed'} onClick={()=>{window.downloads.open(context.item.id);setContext(undefined)}}>Open</button><button disabled={!context.item.savePath} onClick={()=>{window.downloads.showInFolder(context.item.id);setContext(undefined)}}>Open folder</button><span/><button onClick={()=>{window.downloads.copyUrl(context.item.id);setContext(undefined)}}>Copy download address</button><span/><button onClick={()=>{window.downloads.removeFromList(context.item.id);setContext(undefined)}}>Delete from list</button><button className="danger" disabled={!context.item.savePath} onClick={()=>{window.downloads.deleteFromDisk(context.item.id);setContext(undefined)}}>Delete downloaded file</button></div>}
    {detailId&&items.find(item=>item.id===detailId)&&<DownloadProgress item={items.find(item=>item.id===detailId)!} onClose={()=>setDetailId(undefined)}/>} 
  </div>
}

function SchedulerDialog({queues,initialQueue,onClose,onSave,onCreate,onDelete}:{queues:DownloadQueue[];initialQueue:string;onClose:()=>void;onSave:(id:string,name:string,concurrency:number)=>Promise<void>;onCreate:()=>Promise<DownloadQueue>;onDelete:(id:string)=>Promise<DownloadQueue[]>}){
  const [queueId,setQueueId]=useState(initialQueue||queues[0]?.id||''),[name,setName]=useState(queues.find(q=>q.id===initialQueue)?.name??queues[0]?.name??''),[concurrency,setConcurrency]=useState(queues.find(q=>q.id===initialQueue)?.concurrency??1),[message,setMessage]=useState('')
  const queue=queues.find(q=>q.id===queueId)
  function select(id:string){const value=queues.find(q=>q.id===id);setQueueId(id);setName(value?.name??'');setConcurrency(value?.concurrency??1);setMessage('')}
  async function save(close=false){if(!queue)return;await onSave(queue.id,name,concurrency);setMessage('Queue settings saved.');if(close)onClose()}
  async function create(){const created=await onCreate();setQueueId(created.id);setName(created.name);setConcurrency(created.concurrency);setMessage('New queue created. Rename it and press Apply.')}
  async function remove(){if(!queue||queues.length===1){setMessage('At least one queue is required.');return}const remaining=await onDelete(queue.id);const next=remaining[0];setQueueId(next?.id??'');setName(next?.name??'');setConcurrency(next?.concurrency??1);setMessage('Queue deleted. Unfinished files were moved to another queue.')}
  return <div className="dialog-shade"><div className="window-dialog scheduler-dialog"><div className="dialog-title">Scheduler<button onClick={onClose}>×</button></div><div className="scheduler-layout"><aside><div className="queue-tools"><button title="Add queue" onClick={create}>＋</button><button title="Save queue settings" onClick={()=>save(false)}>⚙</button><button title="Delete queue" disabled={queues.length===1} onClick={remove}>×</button></div>{queues.map(q=><button className={q.id===queueId?'selected':''} onClick={()=>select(q.id)} key={q.id}><ListStart/>{q.name}</button>)}</aside><section><div className="schedule-tabs"><button className="active">Schedule</button><button>Files in the queue</button></div><fieldset><legend>Queue settings</legend><label>Queue name <input value={name} onChange={e=>setName(e.target.value)}/></label><label>Download <input type="number" min="1" max="10" value={concurrency} onChange={e=>setConcurrency(Number(e.target.value))}/> files at the same time</label>{message&&<p className="queue-message">{message}</p>}</fieldset><fieldset><legend>Schedule</legend><label className="check"><input type="checkbox"/> Start download at <input type="time" defaultValue="09:00"/></label><div className="weekdays">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(day=><label key={day}><input type="checkbox" defaultChecked/>{day}</label>)}</div><label className="check"><input type="checkbox"/> Stop download at <input type="time" defaultValue="18:00"/></label></fieldset><fieldset><legend>When done</legend><label className="check"><input type="checkbox"/> Hang up modem when done</label><label className="check"><input type="checkbox"/> Exit Internet Download Manager when done</label><label className="check"><input type="checkbox"/> Turn off computer when done</label></fieldset></section></div><div className="dialog-actions"><button onClick={()=>save(false)}>Apply</button><button className="primary" onClick={()=>save(true)}>OK</button><button onClick={onClose}>Cancel</button></div></div></div>
}

function OptionsDialog({segmentCount,onSave,onClose}:{segmentCount:number;onSave:(value:number)=>void;onClose:()=>void}){const tabs=['General','File types','Save to','Downloads','Connection','Proxy / Socks','Site Logins','Dial-Up','Sounds'];const [tab,setTab]=useState('General'),[segments,setSegments]=useState(segmentCount);return <div className="dialog-shade"><div className="window-dialog options-dialog"><div className="dialog-title">Internet Download Manager Configuration<button onClick={onClose}>×</button></div><div className="option-tabs">{tabs.map(name=><button className={tab===name?'active':''} onClick={()=>setTab(name)} key={name}><Settings/>{name}</button>)}</div><div className="option-page"><h3>{tab}</h3>{tab==='Connection'?<><fieldset><legend>Connection type / speed</legend><label>Connection type/speed <select defaultValue="high"><option value="high">High speed: Direct connection</option><option>Medium speed</option><option>Low speed</option></select></label></fieldset><fieldset><legend>Max. connections number</legend><label>Default max. conn. number <select value={segments} onChange={e=>setSegments(Number(e.target.value))}>{[1,2,4,6,8].map(value=><option value={value} key={value}>{value}</option>)}</select></label><p>Each new download will use up to {segments} parallel file segments when the server supports byte ranges.</p></fieldset></>:tab==='General'?<><fieldset><legend>Integrate IDM into browsers</legend><label className="check"><input type="checkbox" defaultChecked/> Launch Internet Download Manager on startup</label><label className="check"><input type="checkbox" defaultChecked/> Use advanced browser integration</label><div className="browser-list"><label><input type="checkbox" defaultChecked/> Microsoft Edge</label><label><input type="checkbox" defaultChecked/> Google Chrome</label><label><input type="checkbox" defaultChecked/> Firefox</label><label><input type="checkbox"/> Opera</label></div></fieldset><fieldset><legend>Customize IDM menu items in context menu of browsers</legend><button>Edit...</button></fieldset></>:<><p>Configure {tab.toLowerCase()} preferences for the download manager.</p><fieldset><legend>{tab} settings</legend><label className="check"><input type="checkbox"/> Enable custom {tab.toLowerCase()} settings</label><label>Default value <input/></label></fieldset></>}</div><div className="dialog-actions"><button className="primary" onClick={()=>onSave(segments)}>OK</button><button onClick={onClose}>Cancel</button><button disabled>Help</button></div></div></div>}

function DownloadProgress({item,onClose}:{item:DownloadItem;onClose:()=>void}){const percent=item.totalBytes?Math.min(100,item.receivedBytes/item.totalBytes*100):0;return <div className="dialog-shade"><div className="window-dialog progress-dialog"><div className="dialog-title">{item.fileName} - Download status<button onClick={onClose}>×</button></div><div className="progress-tabs"><button className="active">Download status</button><button>Speed Limiter</button><button>Options on completion</button></div><div className="progress-info"><label>File name:</label><b>{item.fileName}</b><label>URL:</label><span title={item.url}>{item.url}</span><label>Status:</label><span>{status(item)}</span><label>File size:</label><span>{formatBytes(item.totalBytes)||'Unknown'}</span><label>Downloaded:</label><span>{formatBytes(item.receivedBytes)} ({percent.toFixed(2)}%)</span><label>Transfer rate:</label><span>{item.speed?`${formatBytes(item.speed)}/sec`:'0 B/sec'}</span><label>Time left:</label><span>{timeLeft(item)||'—'}</span><label>Resume capability:</label><span>{item.totalBytes?'Yes':'Unknown'}</span></div><div className="overall-progress"><i style={{width:`${percent}%`}}/></div><div className="segment-head"><b>Connection details</b><span>{item.segmentProgress?.length??item.segmentCount??1} connection(s)</span></div><div className="segments">{(item.segmentProgress??Array.from({length:item.segmentCount??1},()=>0)).map((value,index)=><div className="segment-row" key={index}><span>{index+1}</span><div><i style={{width:`${value}%`}}/></div><em>{item.status==='downloading'?'Receiving data...':item.status}</em><b>{value.toFixed(1)}%</b></div>)}</div><div className="progress-actions"><button onClick={()=>window.downloads.showInFolder(item.id)}>Open folder</button>{item.status==='downloading'?<button className="primary" onClick={()=>window.downloads.pause(item.id)}>Pause</button>:['paused','interrupted','failed'].includes(item.status)?<button className="primary" onClick={()=>window.downloads.resume(item.id)}>Start / Resume</button>:null}<button onClick={()=>{window.downloads.cancel(item.id);onClose()}}>Cancel</button><button onClick={onClose}>Close</button></div></div></div>}

function Tool({icon,label,color,disabled,onClick}:{icon:React.ReactNode;label:string;color:string;disabled?:boolean;onClick?:()=>void}){return <button className={`tool ${color}`} disabled={disabled} onClick={onClick}><span>{icon}</span><small>{label}</small></button>}

function CategoryTree({value,onChange,items,queues,onAdd,onEdit,onDelete}:{value:Category;onChange:(v:Category)=>void;items:DownloadItem[];queues:DownloadQueue[];onAdd:()=>void;onEdit:()=>void;onDelete:()=>void}){
  const rows:Array<[Category,string,React.ReactNode,number?]>=[['all','All Downloads',<Folder/>,items.length],['compressed','Compressed',<FileArchive/>],['documents','Documents',<FileText/>],['music','Music',<Music2/>],['programs','Programs',<Archive/>],['video','Video',<Video/>],['unfinished','Unfinished',<CirclePause/>,items.filter(i=>i.status!=='completed').length],['finished','Finished',<CheckCircle2/>,items.filter(i=>i.status==='completed').length],['queues','Queues',<ListStart/>,queues.length]]
  return <aside className="categories"><div className="pane-title">Categories<div><button title="Add queue" onClick={onAdd}>＋</button><button title="Queue options" onClick={onEdit}>⚙</button><button title="Delete queue" onClick={onDelete}>×</button></div></div><div className="tree">{rows.map(([id,label,icon,count],index)=><button key={id} className={`${value===id?'selected':''} ${index>0&&index<6?'child':''}`} onClick={()=>onChange(id)}>{id==='all'||id==='queues'?<ChevronDown className="chev"/>:<span className="chev"/>}<span className="tree-icon">{icon}</span><span>{label}</span>{count!==undefined&&<em>{count}</em>}</button>)}{queues.map(queue=><button key={queue.id} className={`${value===`queue:${queue.id}`?'selected':''} child`} onClick={()=>onChange(`queue:${queue.id}`)}><span className="chev"/><span className="tree-icon"><ListStart/></span><span>{queue.name}</span><em>{queue.concurrency}×</em></button>)}</div></aside>
}

function DownloadTable({items,selected,onSelect,onOpen,onContext}:{items:DownloadItem[];selected?:string;onSelect:(id:string)=>void;onOpen:(id:string)=>void;onContext:(event:React.MouseEvent,item:DownloadItem)=>void}){
  return <section className="downloads-table"><div className="columns"><span>File Name</span><span>Size</span><span>Status</span><span>Time left</span><span>Transfer rate</span><span>Last Try Date</span><span>Description</span></div><div className="rows">{items.length===0?<div className="no-downloads">There are no files in this category.</div>:items.map(item=><div className={`download-row ${selected===item.id?'selected':''}`} onClick={()=>onSelect(item.id)} onContextMenu={event=>onContext(event,item)} onDoubleClick={()=>onOpen(item.id)} key={item.id}><span className="name"><FileIcon name={item.fileName}/><b>{item.fileName}</b></span><span>{formatBytes(item.totalBytes)}</span><span>{status(item)}</span><span>{timeLeft(item)}</span><span>{item.speed?`${formatBytes(item.speed)}/sec`:''}</span><span>{new Date(item.createdAt).toLocaleString()}</span><span title={item.error}>{item.error??`${item.segmentCount??1} connection(s)`}</span></div>)}</div></section>
}

function FileIcon({name}:{name:string}){const type=ext(name);if(videoTypes.includes(type))return <Video/>;if(archives.includes(type))return <FileArchive/>;if(docs.includes(type))return <FileText/>;if(musicTypes.includes(type))return <Music2/>;return <HardDriveDownload/>}
function status(item:DownloadItem){if(item.status==='completed')return 'Complete';if(item.status==='downloading')return item.totalBytes?`${(item.receivedBytes/item.totalBytes*100).toFixed(2)}%`:'Receiving data...';return item.status[0].toUpperCase()+item.status.slice(1)}
function timeLeft(item:DownloadItem){if(!item.speed||!item.totalBytes)return '';const seconds=Math.max(0,(item.totalBytes-item.receivedBytes)/item.speed);const min=Math.floor(seconds/60);return `${min}:${Math.floor(seconds%60).toString().padStart(2,'0')}`}
function matchesCategory(item:DownloadItem,category:Category){if(category==='all')return true;if(category==='finished')return item.status==='completed';if(category==='unfinished')return item.status!=='completed';if(category==='queues')return Boolean(item.queueId)&&item.status!=='completed';if(category.startsWith('queue:'))return item.queueId===category.slice(6)&&item.status!=='completed';const type=ext(item.fileName);return category==='video'?videoTypes.includes(type):category==='music'?musicTypes.includes(type):category==='documents'?docs.includes(type):category==='compressed'?archives.includes(type):programs.includes(type)}
