import { useEffect,useMemo,useState } from 'react'
import { CirclePause,CirclePlay,Download,FolderOpen,Link,Plus,Search,Trash2 } from 'lucide-react'
import type { DownloadItem,DownloadStatus } from '../shared/download'
const filters:Array<DownloadStatus|'all'>=['all','downloading','completed','paused','interrupted','failed']
const bytes=(value:number)=>value?`${(value/1024/1024).toFixed(value>10*1024*1024?1:2)} MB`:'—'
export function App(){
  const [items,setItems]=useState<DownloadItem[]>([]),[url,setUrl]=useState(''),[filter,setFilter]=useState<DownloadStatus|'all'>('all'),[query,setQuery]=useState(''),[error,setError]=useState('')
  useEffect(()=>{window.downloads.list().then(setItems);return window.downloads.onChanged(setItems)},[])
  const visible=useMemo(()=>items.filter(i=>(filter==='all'||i.status===filter)&&i.fileName.toLowerCase().includes(query.toLowerCase())),[items,filter,query])
  async function add(){try{setError('');await window.downloads.add(url.trim());setUrl('')}catch(e){setError(e instanceof Error?e.message:'Could not add download')}}
  return <div className="shell"><aside><div className="brand"><span><Download size={22}/></span><div>Nexus<small>DOWNLOAD MANAGER</small></div></div><nav>{filters.map(f=><button className={filter===f?'active':''} onClick={()=>setFilter(f)} key={f}><i/>{f[0].toUpperCase()+f.slice(1)}<b>{f==='all'?items.length:items.filter(i=>i.status===f).length}</b></button>)}</nav><div className="storage"><small>DOWNLOAD LOCATION</small><button onClick={()=>window.downloads.openFolder()}><FolderOpen size={17}/> Downloads</button></div></aside>
  <main><header><div><h1>Downloads</h1><p>Manage and monitor your files</p></div><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search downloads"/></div></header><section className="add"><Link size={19}/><input value={url} onChange={e=>setUrl(e.target.value)} onKeyDown={e=>e.key==='Enter'&&add()} placeholder="Paste a download link here…"/><button disabled={!url.trim()} onClick={add}><Plus size={18}/> Add download</button></section>{error&&<p className="error">{error}</p>}<section className="panel"><div className="panelHead"><strong>{visible.length} files</strong><span>{items.filter(i=>i.status==='downloading').length} active</span></div>{visible.length===0?<div className="empty"><div><Download size={38}/></div><h2>No downloads here</h2><p>Paste a direct file URL above to get started.</p></div>:<div className="list">{visible.map(item=><DownloadRow item={item} key={item.id}/>)}</div>}</section></main></div>
}
function DownloadRow({item}:{item:DownloadItem}){const progress=item.totalBytes?Math.min(100,item.receivedBytes/item.totalBytes*100):0;return <article><div className="fileIcon">{item.fileName.split('.').pop()?.slice(0,4).toUpperCase()}</div><div className="file"><strong>{item.fileName}</strong><div className="bar"><span style={{width:`${progress}%`}}/></div><small title={item.error}>{bytes(item.receivedBytes)} of {bytes(item.totalBytes)} · <em className={item.status}>{item.status}</em>{item.speed>0&&` · ${bytes(item.speed)}/s`}{item.error&&` · ${item.error}`}</small></div><div className="percent">{item.status==='completed'?'100%':`${progress.toFixed(0)}%`}</div><div className="actions">{item.status==='downloading'&&<button title="Pause" onClick={()=>window.downloads.pause(item.id)}><CirclePause/></button>}{['paused','interrupted'].includes(item.status)&&<button title="Resume" onClick={()=>window.downloads.resume(item.id)}><CirclePlay/></button>}{!['completed','cancelled','failed'].includes(item.status)&&<button title="Cancel" onClick={()=>window.downloads.cancel(item.id)}><Trash2/></button>}</div></article>}
